sudo: required
services:
  - docker

before_install:
  - docker build -f dockerdev/Dockerfile -t psamsotha/docker-react .

script:
  - docker run psamsotha/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "docker-react-app-dev"
  bucket_name: "elasticbeanstalk-us-west-2-557623108041"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
